#include "../key_util.h"
#include "key_defs.h"
#include <glug_input/keyboard/keys.h>

int code_from_key(enum keys key)
{
    switch (key)
    {
    case glug_key_shift_l:          return gVK_LeftShift;
    case glug_key_shift_r:          return gVK_RightShift;
    case glug_key_alt_l:            return gVK_LeftOption;
    case glug_key_alt_r:            return gVK_RightOption;
    case glug_key_ctrl_l:           return gVK_LeftControl;
    case glug_key_ctrl_r:           return gVK_RightControl;
    case glug_key_super_l:          return gVK_LeftCommand;
    case glug_key_super_r:          return gVK_RightCommand;
    case glug_key_escape:           return kVK_Escape;
    case glug_key_insert:           return kVK_Help;
    case glug_key_home:             return kVK_Home;
    case glug_key_end:              return kVK_End;
    case glug_key_pageup:           return kVK_PageUp;
    case glug_key_pagedown:         return kVK_PageDown;
//    case glug_key_print:            return ??;
//    case glug_key_pause:            return ??;
    case glug_key_backspace:        return kVK_Delete;
    case glug_key_del:              return kVK_ForwardDelete;
    case glug_key_tab:              return kVK_Tab;
    case glug_key_enter:            return kVK_Return;
//    case glug_key_menu:             return ??;
    case glug_key_space:            return kVK_Space;
    case glug_key_up:               return kVK_UpArrow;
    case glug_key_down:             return kVK_DownArrow;
    case glug_key_left:             return kVK_LeftArrow;
    case glug_key_right:            return kVK_RightArrow;
    case glug_key_f1:               return kVK_F1;
    case glug_key_f2:               return kVK_F2;
    case glug_key_f3:               return kVK_F3;
    case glug_key_f4:               return kVK_F4;
    case glug_key_f5:               return kVK_F5;
    case glug_key_f6:               return kVK_F6;
    case glug_key_f7:               return kVK_F7;
    case glug_key_f8:               return kVK_F8;
    case glug_key_f9:               return kVK_F9;
    case glug_key_f10:              return kVK_F10;
    case glug_key_f11:              return kVK_F11;
    case glug_key_f12:              return kVK_F12;
    case glug_key_tilde:            return kVK_ANSI_Grave;
    case glug_key_one:              return kVK_ANSI_1;
    case glug_key_two:              return kVK_ANSI_2;
    case glug_key_three:            return kVK_ANSI_3;
    case glug_key_four:             return kVK_ANSI_4;
    case glug_key_five:             return kVK_ANSI_5;
    case glug_key_six:              return kVK_ANSI_6;
    case glug_key_seven:            return kVK_ANSI_7;
    case glug_key_eight:            return kVK_ANSI_8;
    case glug_key_nine:             return kVK_ANSI_9;
    case glug_key_zero:             return kVK_ANSI_0;
    case glug_key_minus:            return kVK_ANSI_Minus;
    case glug_key_equal:            return kVK_ANSI_Equal;
    case glug_key_a:                return kVK_ANSI_A;
    case glug_key_b:                return kVK_ANSI_B;
    case glug_key_c:                return kVK_ANSI_C;
    case glug_key_d:                return kVK_ANSI_D;
    case glug_key_e:                return kVK_ANSI_E;
    case glug_key_f:                return kVK_ANSI_F;
    case glug_key_g:                return kVK_ANSI_G;
    case glug_key_h:                return kVK_ANSI_H;
    case glug_key_i:                return kVK_ANSI_I;
    case glug_key_j:                return kVK_ANSI_J;
    case glug_key_k:                return kVK_ANSI_K;
    case glug_key_l:                return kVK_ANSI_L;
    case glug_key_m:                return kVK_ANSI_M;
    case glug_key_n:                return kVK_ANSI_N;
    case glug_key_o:                return kVK_ANSI_O;
    case glug_key_p:                return kVK_ANSI_P;
    case glug_key_q:                return kVK_ANSI_Q;
    case glug_key_r:                return kVK_ANSI_R;
    case glug_key_s:                return kVK_ANSI_S;
    case glug_key_t:                return kVK_ANSI_T;
    case glug_key_u:                return kVK_ANSI_U;
    case glug_key_v:                return kVK_ANSI_V;
    case glug_key_w:                return kVK_ANSI_W;
    case glug_key_x:                return kVK_ANSI_X;
    case glug_key_y:                return kVK_ANSI_Y;
    case glug_key_z:                return kVK_ANSI_Z;
    case glug_key_bracket_l:        return kVK_ANSI_LeftBracket;
    case glug_key_bracket_r:        return kVK_ANSI_RightBracket;
    case glug_key_backslash:        return kVK_ANSI_Backslash;
    case glug_key_semicolon:        return kVK_ANSI_Semicolon;
    case glug_key_quote:            return kVK_ANSI_Quote;
    case glug_key_comma:            return kVK_ANSI_Comma;
    case glug_key_period:           return kVK_ANSI_Period;
    case glug_key_slash:            return kVK_ANSI_Slash;
    case glug_key_num_zero:         return kVK_ANSI_Keypad0;
    case glug_key_num_one:          return kVK_ANSI_Keypad1;
    case glug_key_num_two:          return kVK_ANSI_Keypad2;
    case glug_key_num_three:        return kVK_ANSI_Keypad3;
    case glug_key_num_four:         return kVK_ANSI_Keypad4;
    case glug_key_num_five:         return kVK_ANSI_Keypad5;
    case glug_key_num_six:          return kVK_ANSI_Keypad6;
    case glug_key_num_seven:        return kVK_ANSI_Keypad7;
    case glug_key_num_eight:        return kVK_ANSI_Keypad8;
    case glug_key_num_nine:         return kVK_ANSI_Keypad9;
    case glug_key_num_add:          return kVK_ANSI_KeypadPlus;
    case glug_key_num_minus:        return kVK_ANSI_KeypadMinus;
    case glug_key_num_mult:         return kVK_ANSI_KeypadMultiply;
    case glug_key_num_div:          return kVK_ANSI_KeypadDivide;
    case glug_key_num_dec:          return kVK_ANSI_KeypadDecimal;
    case glug_key_none:             // fall-through
    case glug_key_unknown:          break;
    }

    return 0;
}

enum keys glug_key_from_code(int key)
{
    switch (key)
    {
    case gMask_LeftShift:           return glug_key_shift_l;
    case gMask_RightShift:          return glug_key_shift_r;
    case gMask_LeftOption:          return glug_key_alt_l;
    case gMask_RightOption:         return glug_key_alt_r;
    case gMask_LeftControl:         return glug_key_ctrl_l;
    case gMask_RightControl:        return glug_key_ctrl_r;
    case gMask_LeftCommand:         return glug_key_super_l;
    case gMask_RightCommand:        return glug_key_super_r;
    case kVK_Escape:                return glug_key_escape;
    case kVK_Help:                  return glug_key_insert;
    case kVK_Home:                  return glug_key_home;
    case kVK_End:                   return glug_key_end;
    case kVK_PageUp:                return glug_key_pageup;
    case kVK_PageDown:              return glug_key_pagedown;
//    case kVK_PrintScreen:           return glug_key_print;
//    case VK_PAUSE:                  return glug_key_pause;
    case kVK_Delete:                return glug_key_backspace;
    case kVK_ForwardDelete:         return glug_key_del;
    case kVK_Tab:                   return glug_key_tab;
    case kVK_Return:                return glug_key_enter;
//    case kVK_Menu:                  return glug_key_menu;
    case kVK_Space:                 return glug_key_space;
    case kVK_UpArrow:               return glug_key_up;
    case kVK_DownArrow:             return glug_key_down;
    case kVK_LeftArrow:             return glug_key_left;
    case kVK_RightArrow:            return glug_key_right;
    case kVK_F1:                    return glug_key_f1;
    case kVK_F2:                    return glug_key_f2;
    case kVK_F3:                    return glug_key_f3;
    case kVK_F4:                    return glug_key_f4;
    case kVK_F5:                    return glug_key_f5;
    case kVK_F6:                    return glug_key_f6;
    case kVK_F7:                    return glug_key_f7;
    case kVK_F8:                    return glug_key_f8;
    case kVK_F9:                    return glug_key_f9;
    case kVK_F10:                   return glug_key_f10;
    case kVK_F11:                   return glug_key_f11;
    case kVK_F12:                   return glug_key_f12;
    case kVK_ANSI_Grave:            return glug_key_tilde;
    case kVK_ANSI_1:                return glug_key_one;
    case kVK_ANSI_2:                return glug_key_two;
    case kVK_ANSI_3:                return glug_key_three;
    case kVK_ANSI_4:                return glug_key_four;
    case kVK_ANSI_5:                return glug_key_five;
    case kVK_ANSI_6:                return glug_key_six;
    case kVK_ANSI_7:                return glug_key_seven;
    case kVK_ANSI_8:                return glug_key_eight;
    case kVK_ANSI_9:                return glug_key_nine;
    case kVK_ANSI_0:                return glug_key_zero;
    case kVK_ANSI_Minus:            return glug_key_minus;
    case kVK_ANSI_Equal:            return glug_key_equal;
    case kVK_ANSI_A:                return glug_key_a;
    case kVK_ANSI_B:                return glug_key_b;
    case kVK_ANSI_C:                return glug_key_c;
    case kVK_ANSI_D:                return glug_key_d;
    case kVK_ANSI_E:                return glug_key_e;
    case kVK_ANSI_F:                return glug_key_f;
    case kVK_ANSI_G:                return glug_key_g;
    case kVK_ANSI_H:                return glug_key_h;
    case kVK_ANSI_I:                return glug_key_i;
    case kVK_ANSI_J:                return glug_key_j;
    case kVK_ANSI_K:                return glug_key_k;
    case kVK_ANSI_L:                return glug_key_l;
    case kVK_ANSI_M:                return glug_key_m;
    case kVK_ANSI_N:                return glug_key_n;
    case kVK_ANSI_O:                return glug_key_o;
    case kVK_ANSI_P:                return glug_key_p;
    case kVK_ANSI_Q:                return glug_key_q;
    case kVK_ANSI_R:                return glug_key_r;
    case kVK_ANSI_S:                return glug_key_s;
    case kVK_ANSI_T:                return glug_key_t;
    case kVK_ANSI_U:                return glug_key_u;
    case kVK_ANSI_V:                return glug_key_v;
    case kVK_ANSI_W:                return glug_key_w;
    case kVK_ANSI_X:                return glug_key_x;
    case kVK_ANSI_Y:                return glug_key_y;
    case kVK_ANSI_Z:                return glug_key_z;
    case kVK_ANSI_LeftBracket:      return glug_key_bracket_l;
    case kVK_ANSI_RightBracket:     return glug_key_bracket_r;
    case kVK_ANSI_Backslash:        return glug_key_backslash;
    case kVK_ANSI_Semicolon:        return glug_key_semicolon;
    case kVK_ANSI_Quote:            return glug_key_quote;
    case kVK_ANSI_Comma:            return glug_key_comma;
    case kVK_ANSI_Period:           return glug_key_period;
    case kVK_ANSI_Slash:            return glug_key_slash;
    case kVK_ANSI_Keypad0:          return glug_key_num_zero;
    case kVK_ANSI_Keypad1:          return glug_key_num_one;
    case kVK_ANSI_Keypad2:          return glug_key_num_two;
    case kVK_ANSI_Keypad3:          return glug_key_num_three;
    case kVK_ANSI_Keypad4:          return glug_key_num_four;
    case kVK_ANSI_Keypad5:          return glug_key_num_five;
    case kVK_ANSI_Keypad6:          return glug_key_num_six;
    case kVK_ANSI_Keypad7:          return glug_key_num_seven;
    case kVK_ANSI_Keypad8:          return glug_key_num_eight;
    case kVK_ANSI_Keypad9:          return glug_key_num_nine;
    case kVK_ANSI_KeypadPlus:       return glug_key_num_add;
    case kVK_ANSI_KeypadMinus:      return glug_key_num_minus;
    case kVK_ANSI_KeypadMultiply:   return glug_key_num_mult;
    case kVK_ANSI_KeypadDivide:     return glug_key_num_div;
    case kVK_ANSI_KeypadDecimal:    return glug_key_num_dec;
    default:                        return glug_key_none;
    }
}
